name: apiomat-lurker
version: 1.1.0
appVersion: 1.1.0
description: Monitoring for the ApiOmat rest interface Yambas
keywords:
- lurker
- monitoring
- apiomat
- backend
- lowcode
- yambas
home: https://apiomat.com
#icon: 
#sources:
#- 
maintainers:
- name: ApiOmat
  email: containers@apiomat.com