image:
  ## ApiOmat Registry Url
  ##
  registry: docker.io
  ## ApiOmat Lurker image name
  ##
  repository: apiomat/lurker
  ## ApiOmat Lurker image tag
  ## ref: https://hub.docker.com/r/apiomat/lurker/tags/
  ##
  tag: 1.1.0

  ## Specify a imagePullPolicy
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: Always
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  pullSecrets:
    - <regcred>

replicas: 1

ingress:
  enabled: true
  annotations: {}
#    kubernetes.io/ingress.class: "traefik"
  path: /
  hosts:
    - lurker.example.domain

## Kubernetes service type
service:
  annotations: {}
#    traefik.backend.loadbalancer.stickiness: "true"
#    traefik.backend.loadbalancer.method: "drr"
#    traefik.frontend.passHostHeader: "true"
  type: NodePort

# Annotations to be added to Lurker pods
podAnnotations: {}

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
 limits:
#   cpu: 500m
   memory: 4Gi
 requests:
#   cpu: 100m
   memory: 4Gi

## Node selector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}

## Affinity
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

## Tolerations
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

## Configure extra options for liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

# Entries for the Lurker config file
configuration:
  - --spring.cloud.consul.enabled=true --spring.cloud.consul.host=internalurltoconsul --spring.cloud.consul.port=8500  