name: apiomat-instructor
version: 1.1.0
appVersion: 1.1.0
description: Instructor for the ApiOmat rest interface Yambas
keywords:
- inctructor
- docs
- documentation
- apiomat
- backend
- lowcode
- yambas
home: https://apiomat.com
#icon: 
#sources:
#- 
maintainers:
- name: ApiOmat
  email: containers@apiomat.com