kind: Service
apiVersion: v1
metadata:
  name: {{ template "helm.fullname" . }}
  labels:
    app: {{ template "helm.name" . }}
    chart: {{ template "helm.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  ports:
  - name: http
    port: {{ template "helm.port" . }}
    protocol: TCP
  type: {{.Values.service.type }}
  selector:
    app: {{ template "helm.name" . }}
    release: {{ .Release.Name }}